// <auto-generated />
using System;
using LandonWebAPI.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LandonWebAPI.Migrations;

[DbContext(typeof(HotelApiDbContext))]
[Migration("20221123112725_createdDb")]
partial class createdDb
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "6.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

        modelBuilder.Entity("LandonWebAPI.Models.BookingEntity", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<DateTimeOffset>("EndAt")
                    .HasColumnType("datetimeoffset");

                b.Property<DateTimeOffset>("ModifiedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid>("RoomId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("StartAt")
                    .HasColumnType("datetimeoffset");

                b.Property<int>("Total")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("RoomId");

                b.ToTable("Bookings");
            });

        modelBuilder.Entity("LandonWebAPI.Models.RoomEntity", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Rate")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Rooms");
            });

        modelBuilder.Entity("LandonWebAPI.Models.BookingEntity", b =>
            {
                b.HasOne("LandonWebAPI.Models.RoomEntity", "Room")
                    .WithMany()
                    .HasForeignKey("RoomId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Room");
            });
#pragma warning restore 612, 618
    }
}
